spring.application.name=oshibi

# ????DB????
spring.datasource.url=jdbc:postgresql://localhost:5432/oshibi
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA??
spring.jpa.hibernate.ddl-auto=validate

# Flyway??
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ???????????
spring.profiles.active=local

anthropic.api-key=${ANTHROPIC_API_KEY}